name: vvKart
version: '0.1'
main: me.Codex.vvKart.Main
api-version: '1.20.4'
load: STARTUP

commands:
  vvkart:
    description: Main command for vvKart
    usage: /<command> [args]
    aliases: [kart]
  testdisplay:
    description: places a display on the map
    usage: /<command>

permissions:
  vvkart.admin:
    description: Toegang tot alle admin commands
    default: op
  vvkart.reload:
    description: Reload de plugin
    default: op
